language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  directories:
  - node_modules

script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token
  - yarn run test:coverage
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: deploy
