language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn run test
  - yarn run test:coverage
  - yarn run coveralls
  - yarn run build
after_script: # upload coverage reports to coveralls
  - COVERALLS_TOKEN=$coveralls_token
  - yarn run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
